---
name: Terraform

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: fmt
          tf_actions_comment: true

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: init
          tf_actions_comment: true
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        env:
          AWS_DEFAULT_REGION: eu-west-1
        with:
          tf_actions_version: latest
          tf_actions_subcommand: validate
          tf_actions_comment: true

  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        continue-on-error: true # added this to prevent a PR from a remote fork failing the workflow
      - name: Update module usage docs and push any changes back to PR branch
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_args: "--sort-inputs-by-required"
          tf_docs_git_commit_message: "terraform-docs: Update module usage"
          tf_docs_git_push: "true"
          tf_docs_output_file: README.md
          tf_docs_output_method: inject
          tf_docs_find_dir: .
        continue-on-error: true # added this to prevent a PR from a remote fork failing the workflow

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform pr commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.0.2
        with:
          tfsec_args: --concise-output
          github_token: ${{ github.token }}

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.1964.0 # checkov-action v12.1964.0 == checkov 2.2.182 - keep pre-commit and github action in sync
        with:
          container_user: 1000
          directory: "/"
          download_external_modules: true
          framework: terraform
          output_format: sarif
          quiet: true
          skip_check: CKV2_GHA_1
          soft_fail: false